services:
  backend:
    build: .
    container_name: api-vendas-container
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb://mongo:27017/vendasDB
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local